### ISSUE TITLE
[18:47:18][D][DeltaSolivia:028]: FRAME - incorrect header

### ISSUE THREAD

**Issue by fontexD** [robertklep/esphome-delta-solivia#3]
Im using a G3 eu so variant 18

i keep getting this 

[18:47:18][D][DeltaSolivia:028]: FRAME - incorrect header
[18:47:28][D][DeltaSolivia:052]: INVERTER1 - requesting update
[18:47:28][D][DeltaSolivia:028]: FRAME - incorrect header
[18:47:38][D][DeltaSolivia:052]: INVERTER1 - requesting update
[18:47:38][D][DeltaSolivia:028]: FRAME - incorrect header

as of it cant connect to it, what could i be doing wrong ? 
its fine connected to wifi etc, turned on debug mode aswell, 

Used this setup

```
esphome:
  name: 'delta-solivia-reader'
  friendly_name: 'Delta Solivia Reader'
  platformio_options:
    build_unflags: '-std=c++11 -std=gnu++11'
    build_flags: '-std=c++17 -std=gnu++17'

external_components:
  - source: github://robertklep/esphome-delta-solivia@v3.1.0
    components: [ delta_solivia ]

esp32:
  # look here for more information on board ID's:
  # https://esphome.io/components/esp32.html#esp32-platform
  board: esp32dev

# enable logging (entirely optional)
logger:
  level: DEBUG
  baud_rate: 115200

# enable wifi
wifi:
  ssid: "<redacted>"
  password: "<redacted>"

# enable Home Assistant API
api:

# enable over-the-air updates
ota:
  - platform: esphome

# configure a UART (required!)
uart:
  id: solivia_uart
  tx_pin: GPIO2
  rx_pin: GPIO4
  rx_buffer_size: 512
  baud_rate: 19200
  parity: NONE
  stop_bits: 1

# configure the Delta Solivia component
delta_solivia:
  uart_id: solivia_uart       # the id of the UART configured above
  flow_control_pin: GPIO5     # see README.md
  has_gateway: false          # see README.md
  update_interval: 10s        # see README.md
  inverters:
    - address: 1
      variant: 18
      throttle: 30s           # see README.md
      part_number:
        name: 'Inverter#1 Part Number'
      serial_number:
        name: 'Inverter#1 Serial Number'
      ac_power:
        name: 'Inverter#1 Current Power'
      supplied_ac_energy_total:
        name: 'Inverter#1 Total Energy'
      supplied_ac_energy_today:
        name: 'Inverter#1 Today Energy'
        filters:
          - timeout: 2h
      solar_voltage_input_1:
        name: 'Inverter#1 Solar Voltage Input 1'
      solar_current_input_1:
        name: 'Inverter#1 Solar Current Input 1'
      ac_voltage:
        name: 'Inverter#1 AC Voltage'
      ac_current:
        name: 'Inverter#1 AC Current'
      ac_frequency:
        name: 'Inverter#1 AC Frequency'
      ac_grid_voltage:
        name: 'Inverter#1 AC Grid Voltage'
      ac_grid_frequency:
        name: 'Inverter#1 AC Grid Frequency'
      runtime_total:
        name: 'Inverter#1 Runtime Total'
      runtime_today:
        name: 'Inverter#1 Runtime Today'
      max_ac_power_today:
        name: 'Inverter#1 Max AC Power Today'
      max_solar_power_input_1:
        name: 'Inverter#1 Max Solar Power Input 1'
```

Debug UART LOG:
```
9:22:55][D][uart_debug:114]: <<< 00
[19:23:05][D][DeltaSolivia:052]: INVERTER1 - requesting update
[19:23:05][D][uart_debug:114]: >>> 02:05:01:02:60:01:85:FC:03
[19:23:05][D][DeltaSolivia:028]: FRAME - incorrect header
[19:23:05][W][component:239]: Component delta_solivia took a long time for an operation (86 ms).
[19:23:05][W][component:240]: Components should block for at most 30 ms.
[19:23:05][D][uart_debug:114]: <<< 00
[19:23:15][D][DeltaSolivia:052]: INVERTER1 - requesting update
[19:23:15][D][uart_debug:114]: >>> 02:05:01:02:60:01:85:FC:03
[19:23:15][D][DeltaSolivia:028]: FRAME - incorrect header
[19:23:15][W][component:239]: Component delta_solivia took a long time for an operation (86 ms).
[19:23:15][W][component:240]: Components should block for at most 30 ms.
[19:23:15][D][uart_debug:114]: <<< 00
```

**Comment by robertklep** [comment]
Which model do you have specifically?

**Comment by robertklep** [comment]
Are you sure the hardware is set up correctly?

**Comment by fontexD** [comment]
https://ibb.co/c5tCYg7

then on my RJ45 

Pin6 Green
pin7 white/brown

Using a B model Rj45


config

uart:
  id: solivia_uart
  tx_pin: GPIO2
  rx_pin: GPIO4
  rx_buffer_size: 512
  baud_rate: 19200
  parity: NONE
  stop_bits: 1

# configure the Delta Solivia component
delta_solivia:
  uart_id: solivia_uart       # the id of the UART configured above
  flow_control_pin: GPIO5

**Comment by robertklep** [comment]
It looks like the flow control is connected to both GPIO0 and GPIO5? I'm not sure if that might cause issues, GPIO0 often has a special purpose on ESP32s.

If disconnecting from GPIO0 doesn't fix anything, try swapping TX and RX (either the wires, or in the YAML file, but not both).

**Comment by fontexD** [comment]
Ye we removed it so its on 5 now

is the wrigin correct with Green on pin 6 andpin 7 white/brown ?

**Comment by robertklep** [comment]
Yes, the colors sound okay.

The log suggests that the component is trying to send a request to the bus, but it doesn't receive any response.

You can try this:
```
build_flags: '-std=c++17 -std=gnu++17 -DDEBUG_HEADER'
```

It should log additional header data that might be useful in tracking down this issue.

**Comment by fontexD** [comment]
ddint change anything it seems
tried with and withtout gateway on, 
we are using a Wroom 32D
and a rs485 ttl https://ardustore.dk/produkt/max485-til-rs485-converter-adapter-module
checked cables a hundred times, also veried with you they were correct earlier
tried with and withtout flowcontrol connected
D1 lights up but no other led

same response

[18:22:37][D][DeltaSolivia:153]: RESPONSE - timeout
[18:22:47][D][DeltaSolivia:052]: INVERTER1 - requesting update
[18:22:47][D][DeltaSolivia:153]: RESPONSE - timeout
[18:22:57][D][DeltaSolivia:052]: INVERTER1 - requesting update
[18:22:57][D][DeltaSolivia:153]: RESPONSE - timeout

https://ibb.co/n8fQhrYJ
https://ibb.co/pjqpzYmJ
really confused about this tbh, should just work outta da box 

```
esphome:
  name: 'delta-solivia-reader'
  friendly_name: 'Delta Solivia Reader'
  platformio_options:
    build_unflags: '-std=c++11 -std=gnu++11'
    build_flags: '-std=c++17 -std=gnu++17 -DDEBUG_HEADER'


external_components:
  - source: github://robertklep/esphome-delta-solivia@v3.1.0
    components: [ delta_solivia ]

esp32:
  # look here for more information on board ID's:
  # https://esphome.io/components/esp32.html#esp32-platform
  board: esp32dev

# enable logging (entirely optional)
logger:
  level: VERBOSE
  baud_rate: 0

# enable wifi
wifi:
  ssid: "Fontex_iot"
  password: "<redacted>"

# enable Home Assistant API
api:

# enable over-the-air updates
ota:
  - platform: esphome

# configure a UART (required!)
uart:
  id: solivia_uart
  tx_pin: GPIO1
  rx_pin: GPIO3
  rx_buffer_size: 512
  baud_rate: 19200
  parity: NONE
  stop_bits: 1

# configure the Delta Solivia component
delta_solivia:
  uart_id: solivia_uart       # the id of the UART configured above
  flow_control_pin: GPIO22    
  has_gateway: true          # see README.md
  update_interval: 10s        # see README.md
  inverters:
    - address: 1
      variant: 18
      throttle: 30s           # see README.md
      part_number:
        name: 'Inverter#1 Part Number'
      serial_number:
        name: 'Inverter#1 Serial Number'
      ac_power:
        name: 'Inverter#1 Current Power'
      supplied_ac_energy_total:
        name: 'Inverter#1 Total Energy'
      supplied_ac_energy_today:
        name: 'Inverter#1 Today Energy'
        filters:
          - timeout: 2h
      solar_voltage_input_1:
        name: 'Inverter#1 Solar Voltage Input 1'
      solar_current_input_1:
        name: 'Inverter#1 Solar Current Input 1'
      ac_voltage:
        name: 'Inverter#1 AC Voltage'
      ac_current:
        name: 'Inverter#1 AC Current'
      ac_frequency:
        name: 'Inverter#1 AC Frequency'
      ac_grid_voltage:
        name: 'Inverter#1 AC Grid Voltage'
      ac_grid_frequency:
        name: 'Inverter#1 AC Grid Frequency'
      runtime_total:
        name: 'Inverter#1 Runtime Total'
      runtime_today:
        name: 'Inverter#1 Runtime Today'
      max_ac_power_today:
        name: 'Inverter#1 Max AC Power Today'
      max_solar_power_input_1:
        name: 'Inverter#1 Max Solar Power Input 1'
```
